=== san2488/sernlabs/includes/aboutpage/aboutpage.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--

    PUBLIC ID: -//sernlabs//draft//EN
    SYSTEM ID: http://server/path/about_aboutsite1.dtd

-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT page (title, keywords, description, section*)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT title (#PCDATA)>

<!ELEMENT keywords(keyword*)>

<!ELEMENT keyword(#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT description (#PCDATA|p)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT section (title, content)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT content (#PCDATA|p|pre|code|img|a)*>

<!-- Expected HTML Elements -->
<!ELEMENT p (#PCDATA|img|a)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT pre (#PCDATA|code)*>
<!ELEMENT code (#PCDATA)>
<!ELEMENT img EMPTY>

<!ATTLIST a href CDATA #REQUIRED>

=== san2488/sernlabs/includes/aboutpage/aboutsite1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "aboutpage.dtd">
<page url="AboutSite1.php">
    <title>About Site</title>
    <description>
        The purpose of the About Site page is to give you an overall idea about SERNLabs, 
          or may be not. Okay, I know you have had enough of that! 
          But the feature I tried out on this page is the CSS @font-face tag.
    </description>       
    <keywords>
        <keyword>@font-face</keyword>
        <keyword>embed fonts</keyword>
        <keyword>fonts</keyword>
        <keyword>About Sernlabs</keyword>
        <keyword>Typewriter</keyword>
        <keyword>Handwriting</keyword>
    </keywords>
    <section>
        <title>The Code</title>
        <content>
            <![CDATA[
            <p>The @font-face tag allows you to embed your own fonts into the webpage. 
          Fonts on the web have always been a tricky affair. You might use the most 
          attractive of fonts while designing the page, but if the same font is not
          available on the user's machine, then the browser will replace it with a font it deems fit. 
          Not a very good prospect for a carefully designed page. The @font-face tag can fix that.
            </p>
            <p>The @font-face tag syntax I have used is pretty simple:</p>
<pre><code>@font-face {
    font-family: 'TravelingTypewriter';
    src: url('../fonts/TravelingTypewriter.eot');
    src: url('../fonts/TravelingTypewriter.eot?#iefix') format('embedded-opentype'),
         url('../fonts/TravelingTypewriter.ttf') format('truetype');
}
@font-face {
    font-family: 'honey';
    src: url('../fonts/honey.eot');
    src: url('../fonts/honey.eot?#iefix') format('embedded-opentype'),
         url('../fonts/honey.ttf') format('truetype');
}</code></pre>
      The core syntax is even simpler actually:
<pre><code>@font-face {
    font-family: 'TravelingTypewriter';
    src: url('TravelingTypewriter.otf');
}</code></pre>
            <p>But there are issues with Cross-browser compatiability that need the 
      additional lines of code. 
          Those issues are documented here, 
                <a href="http://webfonts.info/wiki/index.php?title=@font-face_browser_support">
              Webfonts.info - @font-face Browser Support
                </a>.
            </p>
            <p></p>
            <p>Fear not though, dealing with cross-browser compatiable @font-face tags 
          is made very easy by this wonderful tool, 
                <a href="http://www.fontsquirrel.com/fontface/generator">Font Squirrel
          - @font-face generator
                </a>. Another resource I found particulary helpful
          is 
                <a href="http://randsco.com/index.php/2009/07/04/p680">Randsco.com 
          - How @font-face Works: Easy Peasy
                </a>. As always, googling @font-face
          remains your best bet.
            </p>]]>
        </content>
    </section>
    <section>
        <title>The Design</title>
        <content>
            <![CDATA[
            <p>About the Design aspect of the page, I wanted a clean design to offset 
          the craziness of the text that it was supposed to contain. The colour 
          theme is similar to the Homepage so as not to immediately shock users.
          The sidebar font was supposed to reflect my actual handwriting, but I 
          just could not find anything bad enough!
            </p>
            ]]>
        </content>
    </section>
    <section>
        <title>External Links</title>
        <content>
            <![CDATA[
            <p id="externalLinks">
                
            </p>
            ]]>
        </content>
    </section>
</page>

=== san2488/sernlabs/includes/aboutpage/aboutpage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "aboutpage.dtd">
<page>
    <title>About Page</title>
    <description>
        The About Page page is a lot of things. It is primarily to explain what 
        is going on behind-the-scenes on any page. I won't go into very fine details.
        Rather, just expect enough here to get you started on any topic. You can 
        follow the links I mention to get more details. This is also the first page 
        I created in SERNLabs with PHP in it. Plus there is also a XML-XSL framework 
        for storing content and of course there's the jQuery.
    </description>    
    <keywords>
        <keyword>XML</keyword>
        <keyword>PHP</keyword>
        <keyword>XSLT</keyword>
        <keyword>XSL</keyword>
        <keyword>XSL Transform</keyword>
        <keyword>DTD</keyword>
        <keyword>external links</keyword>
        <keyword>fixed background</keyword>
        <keyword>&lt;xsl:for-each&gt;</keyword>
        <keyword>&lt;xsl:value-of&gt;</keyword>
    </keywords>
    <section>
        <title>The Code</title>
        <content>
            <![CDATA[
            <p>There is supposed to be an About Page page for every page in SERNLabs,
            even for the About Page (that's what you are reading right now 
            (recursion! drives me crazy too ;-) )). I really didn't want to maintain 
            a whole HTML page for every page I create. So, I decided to use PHP, 
            XML and XSL to separate out the variable content from the static design.</p>
            <p>So, what I ended up with was a series of XML pages that stored the 
            HTML and raw text. Something like this:</p>
            
<pre><code>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;!DOCTYPE page SYSTEM &quot;about_page.dtd&quot;&gt;
&lt;page&gt;
    &lt;title&gt;&lt;/title&gt;
    &lt;description&gt;
    &lt;/description&gt;
    &lt;section&gt;
        &lt;title&gt;&lt;/title&gt;
        &lt;content&gt; 
        &lt;/content&gt;
    &lt;/section&gt;
&lt;/page&gt;</page></code></pre>

            <p>I guess this is pretty self-explanatory. For any help on XML always remember <a href="http://w3schools.com">W3Schools</a>.</p>
            <p>Then, I designed some XSL mark up to help render the content of those XMLs:</p>
<pre><code>&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
    &lt;xsl:template match=&quot;/&quot;&gt;
            &lt;div id=&quot;container&quot;&gt;
                &lt;div id=&quot;mainContent&quot;&gt;
                    &lt;div id=&quot;actualContent&quot;&gt;
                        &lt;h1&gt;
                            About &lt;xsl:value-of select=&quot;page/title&quot;/&gt; Page
                        &lt;/h1&gt;
                        &lt;p&gt;
                            &lt;xsl:value-of disable-output-escaping=&quot;yes&quot; 
                            select=&quot;page/description&quot;/&gt;
                        &lt;/p&gt;
                        &lt;xsl:for-each select=&quot;page/section&quot;&gt;
                            &lt;h3&gt;
                                &lt;xsl:value-of select=&quot;title&quot; /&gt;
                            &lt;/h3&gt;
                            &lt;xsl:value-of disable-output-escaping=&quot;yes&quot; select=&quot;content&quot; /&gt;
                        &lt;/xsl:for-each&gt;
                    &lt;/div&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/xsl:template&gt;
&lt;/xsl:stylesheet&gt; 
</code></pre>
         <p>XSL is pretty comprehensively explained at 
         <a href="http://www.w3schools.com/xsl/default.asp">W3Schools XSLT Tutorial</a>.</p>
         <p>The next challenge was to combine the XSL and XML to dynamically 
         render pages. This can be done through 
         <a href="http://www.w3schools.com/xsl/xsl_client.asp">XSLT on Client using Javascript</a> or 
         through <a href="http://www.w3schools.com/xsl/xsl_server.asp">XSLT on Server</a>.
         I was averse to dealing with Browser-specific rendering issues later, 
         and so decided to opt for the latter using PHP. W3Schools falls a litte
         short here since their examples for XSL Transformation use ASP. But I 
         found the required info at 
         <a href="http://www.sitepoint.com/transform-php-xslt/">Sitepoint.com's Transform your PHP with XSLT</a>.</p>
         <p>The final code was pretty simple:</p>
<pre><code>$doc = new DOMDocument();
$xsl = new XSLTProcessor();

$doc-&gt;load(&quot;../includes/aboutpage/aboutpage.xsl&quot;);
$xsl-&gt;importStyleSheet($doc);

$page = $_GET[&quot;pg&quot;];
$page = explode(&quot;.&quot;, $page);
$page = $page[0];
$page = &quot;includes/data/&quot; . $page . &quot;.xml&quot;;
$doc-&gt;load($page);
echo $xsl-&gt;transformToXML($doc);</code></pre>
            <p>One major catch was that the PHP XSLT Parser parsed the HTML that 
            I wanted to display as is. I got around this by storing the HTML in 
            the XSL withing CDATA blocks. CDATA blocks are not parsed by the 
            parser. This was the best solution I found to maintain the readability 
            the XMLs:</p>
<pre><code>&lt;![CDATA[
    &lt;p&gt;There is supposed to be an About Page page for every page in SERNLabs,
    even for the About Page (that&#39;s what you are reading right now 
    (recursion! drives me crazy too ;-) )). I really didn&#39;t want to maintain 
    a whole HTML page for every page I create. So, I decided to use PHP, 
    XML and XSL to separate out the variable content from the static design.&lt;/p&gt;
    &lt;p&gt;So, what I ended up with was a series of XML pages that stored the 
    HTML and raw text. Something like this:&lt;/p&gt;
]]&gt;</code></pre>
            ]]>
        </content>
    </section>
    <section>
        <title>The Design</title>
        <content>
            <![CDATA[
            <p>This page just had to be simple. There could be not distractions 
            from the (hopefully) useful content. Simple and Sombre were the keywords.</p>
            <p>The fixed background is achieved through:</p>
<pre><code>body {
    background:url(../images/AboutPage_BG.jpg) fixed no-repeat #000;
}</code></pre>
            <p>The most interesting feature with respect to the design was the 
            External Links section. I decided to create its content entirely dynamically 
            on the Client. But first I had to identify the external links that 
            I was adding to the page. This was made easy by a 
            <a href="http://jquery-howto.blogspot.com/2009/06/find-select-all-external-links-with.html">jQuery Blog on Blogspot</a>.</p>
<pre><code>$.expr[&#39;:&#39;].external = function(obj){
    return !obj.href.match(/^mailto\:/) &amp;&amp; (obj.hostname != location.hostname);</code></pre>
    <p>All that was left, was to append the links found to the External Links section:</p>
<pre><code>$(document).ready(function() {
    var extlinks = $(&quot;a:external&quot;);
    $.each(extlinks, function(i, link){
        $(&quot;#externalLinks&quot;).append($(link).clone().attr(&quot;target&quot;,&quot;_blank&quot;)).append(&quot;&lt;br /&gt;&quot;);
    });
});</code></pre>
            ]]>
        </content>
    </section>
    <section>
        <title>External Links</title>
        <content>
            <![CDATA[
            <p id="externalLinks">
                
            </p>
            ]]>
        </content>
    </section>
</page>

=== san2488/sernlabs/includes/aboutpage/homepage1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "aboutpage.dtd">
<page url="HomePage1.php">
    <title>Home Page</title>
    <description>
        This is the home page, mother page, landing page, etc for the site. This
        will probably be the first page that most people visit and link to,
        consequently the highest PageRanked page.
    </description>
    <keywords>
        <keyword>CSS Rollover</keyword>
        <keyword>Mobile CSS</keyword>
        <keyword>iPhone</keyword>
        <keyword>media</keyword>
        <keyword>viewport</keyword>
        <keyword>&lt;meta&gt;</keyword>
    </keywords>
    <section>
        <title>The Code</title>
        <content>
            <![CDATA[

            <p>This page has no Javascript and no complex PHP. The file extension 
            is PHP more for conformance than for functionality. The twitchy 
            wooden boards effect is an easy CSS trick. If you want to see how 
            that's done check out the About Page for my <a href="AboutMe1.php">
            About Me</a> page.</p>

            ]]>
        </content>
    </section>
    <section>
        <title>The Design</title>
        <content>
            <![CDATA[
            
            <p>I am a sucker for Orange (the color, not the fruit). So the copious 
            amounts of the same (the color, not the fruit) on this page. But I 
            must admit that I have lifted most of the design idea from another
            site. I am not going to reveal from where for avoiding comparisons
            (and the fact that the original looks way better). But, if you do 
            find that site, let me know.</p>
            
            <p>This is the first page of the website that I decided to  optimize for
            mobile viewing. Since, this is the first page of the website, that 
            decision was a no-brainer. Also, once you get the basics in place,
            making the page work with mobile devices doesn't require much 
            ingenuity. One of the basic elements that it does require is the 
            Viewport Meta tag. This tag is read by mobile browsers to determine
            what part of the page to display initially and the zoom-in range.</p>
            
<pre><code>&lt;meta name=&quot;viewport&quot; 
    content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt; 
</code></pre>            

            <p>The content attribute holds most of the required parameters. The 
            device-width value is a useful attribute to dynamically set the 
            viewport to width of the mobile device. The scale values determine 
            the zoom-in levels. The concept of viewport is covered nicely in
            <a href='https://developer.apple.com/library/safari/#documentation/appleapplications/reference/safariwebcontent/usingtheviewport/usingtheviewport.html'>
            Apple's Docmentation on Viewports</a>.</p>
            
            <p>Apart from the viewport, its was also necessary to tweak the 
            style-sheet of the page to cater to smaller screens. This is done 
            using a separate stylesheet added to the page as follows:</p>
            
<pre><code>&lt;link rel=&quot;stylesheet&quot; href=&quot;stylesheets/homepage1.css&quot; type=&quot;text/css&quot; media=&quot;Screen&quot; /&gt;
&lt;link rel=&quot;stylesheet&quot; href=&quot;stylesheets/mobile/homepage1.css&quot; type=&quot;text/css&quot; 
    media=&quot;handheld, only screen and (max-width: 480px), 
            only screen and (max-device-width: 480px)&quot; /&gt;
</code></pre>
            
            <p>The media='Screen' attribute indicates that the stylesheet is 
            targetted for Desktop and media='handheld' indicates mobile devices.
            But the problem is that most modern mobile browsers won't fall for this
            and will still end up using the Screen stylesheet. To target them, 
            we need to determine the stylesheet depending on teh screen size. The 
            width is specified as 480px because that is the landscape mode width 
            non-Retina display iPhones. But most Android and retina display iPhones
            will work with this resolution just fine. Targetting for mobile devices
            is explained in a no-nonsense way at <a href='http://www.seabreezecomputers.com/tips/mobile-css.htm'>
            SeaBreezeComputer.com's Mobile CSS tips</a>. But an even more useful
            and generic guide is <a href='http://perishablepress.com/press/2009/08/02/the-5-minute-css-mobile-makeover/'>
            Perishable Press' 5-minute CSS makeover</a>.</p>
            ]]>
        </content>
    </section>
    <section>
        <title>External Links</title>
        <content>
            <![CDATA[
            <p id="externalLinks">
                
            </p>
            ]]>
        </content>
    </section>
</page>

=== san2488/sernlabs/includes/aboutpage/photogallery1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "aboutpage.dtd">
<page url="PhotoGallery1.php">
    <title>Photo Gallery</title>
    <description>
        I am a hobbyist Photographer and it would have been blasphemous not to 
        show off of my pics on my own site.
    </description>
    <keywords>
        <keyword>Photos</keyword>
        <keyword>Photography</keyword>
        <keyword>XML</keyword>
        <keyword>PHP XML</keyword>
        <keyword>Simple XML</keyword>
        <keyword>Carousal</keyword>
        <keyword>jQuery</keyword>
        <keyword>Popup</keyword>
    </keywords>
    <section>
        <title>The Code</title>
        <content>
            <![CDATA[
            <p>I am pretty much in love with XML and this was good place to use
            it. The image, apart from the source url was supposed to also contain
            some meta-data like the caption, orientation, etc. The XML structure
            used is:</p>
        <pre><code>&lt;photo orientation=&quot;1&quot; id=&quot;p2&quot;&gt;
    &lt;src&gt;images/Photos/Spiti00017.jpg&lt;/src&gt;
    &lt;caption&gt;Some Caption&lt;/caption&gt;
&lt;/photo&gt;</code></pre>
        <p>PHP has some really awesome inbuilt functions to read XML. These were
        really easy to use. No wonder its called SimpleXML. For more information
        check out the <a href="http://php.net/manual/en/book.simplexml.php" target="_blank">Manual
        for SimpleXML</a>.</p>
        <p>To read an element, all you need is:</p>
        <pre><code>$src = $photo-&gt;src</code></pre>
        <p>To read an attribute, all you need is:</p>
        <pre><code>$orientation = $photo-&gt;attributes()-&gt;orientation</code></pre>
        <p>The final code was:</p>
        <pre><code>&lt;?php
    $photosFile = simplexml_load_file(&quot;../includedFiles/Info.xml&quot;);
    $photos = $photosFile-&gt;photo;
    foreach($photos as $photo)
    {
        $src = $photo-&gt;src;
        $alt = $photo-&gt;alt;
        $orientation = $photo-&gt;attributes()-&gt;orientation;
        $caption = htmlspecialchars($photo-&gt;caption, ENT_QUOTES);

        echo &quot;&lt;div class=&#39;photo&#39; 
            style=&#39;background-image: url(\&quot;$src\&quot;); 
            data-orientation=&#39;$orientation&#39; 
            data-caption=&#39;$caption&#39;&gt;&quot; . &quot;&lt;/div&gt;&quot;;
    }
?&gt;</code></pre>
        <p>I am using the data-orientation and data-caption attributes to store
        meta-data. This is a new feature of the HTML5 spec and its really 
        useful!</p>
        <p>Data attributes can be read using jQuery simply as:</p>
        <pre><code>$self.data(&quot;orientation&quot;)</code></pre>
            
            ]]>
        </content>
    </section>
    <section>
        <title>The Design</title>
        <content>
            <![CDATA[
            
            <p>The design for this page had to be pleasing but mundane. Otherwise, no
            one is going to be interested in the photos! I initially had a 
            different design in mind which included a background filled with an 
            image of my dear Canon SX20. But that started becaming too tacky, even for
            my own distinguished taste.</p>
            <p>So I went to one of the back-up designs I had in mind. The 
            center piece of the new design was supposed to be the thumbnail view.
            That turned out to be pretty easy to achieve using some good-old
            jQuery:</p>
<pre><code>$(".photo").hover(function(){
   var $self = $(this);
   var photoWidth = $self.data("orientation") == 1?400:225;

   $self.stop().animate({width:photoWidth}, 300);
   $self.siblings('.photo.active').stop().animate({width:40}, 500).removeClass('active');
   $self.addClass('active');
})</code></pre>
            <p>I also wanted a full-size view on clicking a thumbnail image. I 
            had to reach out to <a href="http://jqueryui.com/demos/dialog/" 
            target="_blank">jQuery UI Dialog Box</a> for that:</p>
<pre><code>var $photoDialog = $("#photo-dialog").dialog({
    dialogClass: 'photoDialog',
    modal: true,
    width: 840,
    height: 620
});</code></pre>
            <p>There are other minor effects on this page that I won't be 
            explaining here. You could just go through the Page Source for that.
            All in all, what I liked best about this page was that it looked so good 
            without having me to spend too much time on it.</p>
            
            ]]>
        </content>
    </section>
    <section>
        <title>External Links</title>
        <content>
            <![CDATA[
            <p id="externalLinks">
                
            </p>
            ]]>
        </content>
    </section>
</page>

=== san2488/sernlabs/includes/aboutpage/aboutme1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "aboutpage.dtd">
<page url="AboutMe1.php">
    <title>About Me</title>
    <description>
        This page is all about I, me and myself.
    </description>
    <keywords>
        <keyword>jQuery</keyword>
        <keyword>iPhone</keyword>
        <keyword>sujay narsale</keyword>
        <keyword>iOS</keyword>
        <keyword>Accordian</keyword>
        <keyword>CSS Rollover</keyword>
        <keyword>Easter Eggs</keyword>
    </keywords>
    <section>
        <title>The Code</title>
        <content>
            <![CDATA[
            <p>There is no PHP gimmickry on this page. Its all about jQuery 
            Glory. I didn't know much jQuery at all when I started off with this
            page. But by the end of it, I had become quite the expert! This page
            took the most time to create - by far!</p>
            <p>The center piece of the show - the iPod - was the hardest to 
            make. It took a lot of small effects to make it seem just a little
            like the iOS interface. The basic structure for the iPod is a 
            <a href="http://docs.jquery.com/UI/Accordion">jQuery Accordian</a>
            look-alike, with a &ltspan&gt for the content 
            and a &lth3&gt for the triggering button:</p>
<pre><code>&lt;span style=&quot;background-color:#C0F&quot; class=&quot;ipodSlideWindow&quot;&gt;
&lt;div&gt;
&lt;div class=&quot;ipodHeader ipodHdrBlue&quot;&gt;Misc&lt;/div&gt;
&lt;div style=&quot;padding:5px;&quot;&gt;
  &lt;table class=&quot;ipodIntro&quot;&gt;
    &lt;tr&gt;
      &lt;td&gt;&lt;img src=&quot;images/AboutMe1/127410-simple-black-square-.png&quot; 
        class=&quot;ipodBoxImage&quot; alt=&quot;expert&quot; /&gt;&lt;/td&gt;
      &lt;td&gt;In a few words&lt;/td&gt;
    &lt;/tr&gt;
  &lt;/table&gt;
  &lt;table class=&quot;ipodForm&quot; cellspacing=&quot;0&quot;&gt;
    &lt;tr&gt;
      &lt;td style=&quot;width:0%;&quot;&gt;&lt;/td&gt;
      &lt;td style=&quot;text-transform:none; text-align:justify;&quot;&gt;I am 
      currently working at TCS under a project for Genworth Wealth
      Management. This developer profile involves work in the latest 
      MS technologies. Very exciting stuff!&lt;br /&gt;
        &lt;br /&gt;
        SernLabs is just for TP so that I can stay in touch with 
        CSS, JS and Photoshop. It also provides good motivation to 
        try out new things.&lt;br /&gt;
        &lt;br /&gt;
        I read somewhere that its good to have your mug pasted on 
        your site....so here goes.&lt;/td&gt;
    &lt;/tr&gt;
  &lt;/table&gt;
  &lt;table class=&quot;ipodForm&quot; cellspacing=&quot;0&quot;&gt;
    &lt;tr class=&quot;ipodLink&quot; id=&quot;mugShot&quot;&gt;
      &lt;td class=&quot;ipodLabel&quot;&gt;&lt;img 
          src=&quot;images/AboutMe1/more_realistic_icons.jpg&quot; width=&quot;20&quot; 
          height=&quot;20&quot; alt=&quot;photo&quot; /&gt;&lt;/td&gt;
      &lt;td&gt;My Mugshot&lt;/td&gt;
    &lt;/tr&gt;
    &lt;tr class=&quot;ipodLink&quot;&gt;
      &lt;td class=&quot;ipodLabel&quot;&gt;&lt;img 
        src=&quot;images/AboutMe1/iossettings.png&quot; width=&quot;20&quot;
        height=&quot;20&quot; alt=&quot;settings&quot; /&gt;&lt;/td&gt;
      &lt;td&gt;About Page&lt;/td&gt;
    &lt;/tr&gt;
  &lt;/table&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/span&gt;
&lt;h3 class=&quot;ipodNavButton&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;span&gt;Misc&lt;/span&gt;&lt;img 
src=&quot;images/AboutMe1/ipodTabIcon_misc.png&quot; width=&quot;83&quot;
height=&quot;115&quot; /&gt;&lt;/a&gt;&lt;/h3&gt;</code></pre>
<p>On the day I finished most of the functionality for this page, I found the
<a href="http://iphone.hohli.com/">jQuery iPhone UI</a>. This does almost 
everything that I was aiming for and feels truely awesome! Only if I had met you
earlier! But anyway, I did it my own way. Some basic jQuery took care of the 
sliding effect.</p>
<pre><code>$(&quot;.ipodPane h3&quot;).click(function() 
{			
    $(this).addClass(&quot;viewing&quot;);
    $(&quot;.ipodPane h3&quot;).not($(this)).removeClass(&quot;viewing&quot;);
    refreshViewPane($(this).siblings().css(&#39;left&#39;) == 0 + &quot;px&quot; ? 0 : paneWidth);
});

function refreshViewPane(initLeft){
    $(&quot;.ipodPane h3.viewing&quot;).siblings().css(&#39;left&#39;, initLeft + &quot;px&quot;);
    $(&quot;.ipodPane h3.viewing&quot;).siblings().animate({
        left: &quot;0px&quot;
    },&#39;fast&#39;,&#39;swing&#39;);
    $(&quot;.ipodPane span.ipodSlideWindow&quot;).not($(&quot;h3.viewing&quot;).siblings()).animate({
        left: -paneWidth + &quot;px&quot;
        },&#39;fast&#39;,&#39;swing&#39;);

    $(&quot;.ipodPane h3.viewing&quot;).find(&quot;img&quot;).css(&#39;margin-top&#39;, -tabImgHt / 2 + &#39;px&#39;);
    $(&quot;.ipodPane h3.viewing&quot;).find(&quot;span&quot;).css(&#39;color&#39;, &#39;#FFF&#39;);

    $(&quot;.ipodPane h3&quot;).not(&quot;.viewing&quot;).find(&quot;img&quot;).css(&#39;margin-top&#39;, &#39;0px&#39;);
    $(&quot;.ipodPane h3&quot;).not(&quot;.viewing&quot;).find(&quot;span&quot;).css(&#39;color&#39;, &#39;#7c7c7c&#39;);
}</code></pre>
           ]]>
        </content>
    </section>
    <section>
        <title>The Design</title>
        <content>
            <![CDATA[
            <p>No prizes for guessing what this page design is inspired from.
            Its a lot cleaner than my desk in reality though! Some of the pics I 
            got from a simple Google Search while others I clicked myself. The 
            shadow effect images were created with Photoshop.</p>
            <p>One trick that I use a lot is the Pure CSS Button Rollover. You 
            can see this effect on the iPod main navigation buttons. This 
            involves creating a image double the height of your intended button
            and having both the Mouseover and Mouseout graphics in the same image.
            Something like this:</p>
            <img src="images/AboutMe1/ipodTabIcon_info.png" alt="CSS Hover Example image"
            class="aboutImg"></img>
            <p>Then we set the CSS to show only half the image and shift it 
            cleverly on hover.</p>
<pre><code>.ipodPane h3 {
    margin: 0 auto; 
    position:absolute;	
    width: 25%;
    height: 12%;
    bottom: 0px;
    overflow:hidden;
    background:url(../images/AboutMe1/ipodTabIcon_02.png) #000 repeat-x;
}
.ipodPane h3:hover img{
	margin-top: -55px;
}</code></pre>
            <p>A variation of this trick is to set the required image as the 
            background-image and then shift the background-position accordingly.
            I like this effect because it involves no jQuery and will work on the
            most ancient browsers imaginable. For more details on this effect 
            have a look at 
            <a href="http://www.webvamp.co.uk/blog/coding/graphical-css-rollover-menu/">
                WebVamp's Graphical CSS Rollover Menu</a>.</p>
                <p>Also, this page is going to be home to a lot of Easter Eggs.
                I am not going to say more, because otherwise they would be just
                plain eggs. You don't want those!</p>
                ]]>
        </content>
    </section>
    <section>
        <title>External Links</title>
        <content>
            <![CDATA[
            <p id="externalLinks">
                
            </p>
            ]]>
        </content>
    </section>
</page>
